(vl-load-com)
(setvar "ACADLSPASDOC" 1)
;; zwk:root is supplied by the installer/startup hook, never *load-truename*.
;; Distribution file is GBK encoded.
(defun zwk:bridge (cmd / path f value)
  (setq path (strcat (getenv "TEMP") "/zwkit-bridge-102.txt"))
  (if (findfile path) (vl-file-delete path))
  (command cmd)
  (if (setq f (open path "r"))
    (progn (setq value (read (read-line f))) (close f) value)
    nil))
(defun zwk:ready () (equal (zwk:bridge "ZWKREADY102") '("READY")))
(defun zwk:smooth (/ old v)
  (setq v (getvar "VIEWRES"))
  (if (or (null v) (/= v 20000))
    (progn
      (setq old (getvar "CMDECHO"))
      (setvar "CMDECHO" 0)
      (command "_.VIEWRES" "_Y" 20000)
      (setvar "CMDECHO" old))))
(defun zwk:smooth-value () (zwk:bridge "ZWKSMOOTH102"))
(defun zwk:selection-ok ()
  (and zwk:enabled
    (or (not (member "dimensions" zwk:enabled)) c:ZD)
    (or (not (member "trim" zwk:enabled)) c:TR)
    (or (not (member "extend" zwk:enabled)) c:EX)
    (or (not (member "tolerance" zwk:enabled)) c:GC)
    (or (not (member "symbols" zwk:enabled)) c:FH)
    (or (not (member "font" zwk:enabled)) c:ZF)
    (or (not (member "dimline" zwk:enabled)) c:BZ)))
(defun zwk:enabled-str (/ s)
  (setq s "")
  (foreach zwk:e zwk:enabled (setq s (strcat s zwk:e " ")))
  (if (= s "") "无" s))
(defun c:ZWKCHECK ()
  (princ (strcat "\n工具包 1.2，自检模块=" (if (zwk:ready) "就绪" "未就绪")
    "，平滑度=" (itoa (zwk:smooth-value)) "，已启用：" (zwk:enabled-str))) (princ))
(if (and zwk:root (findfile (strcat zwk:root "/modules.lsp")))
  (progn
    (command "_.NETLOAD" (strcat zwk:root "/bin/ZWKit.Core.102.dll"))
    (setq zwk:enabled '("dimensions" "trim" "extend" "tolerance" "symbols" "font" "dimline"))
    (if (findfile (strcat zwk:root "/selection.lsp")) (load (strcat zwk:root "/selection.lsp")))
    (load (strcat zwk:root "/modules.lsp"))
    ;; EXD's Shift-drag reuses trim.lsp's zt:trim, so picking "extend" alone
    ;; still needs trim.lsp loaded -- but ZT/TRD stay hidden below unless
    ;; "trim" itself was actually selected.
    (setq zwk:loadset zwk:enabled)
    (if (and (member "extend" zwk:loadset) (not (member "trim" zwk:loadset)))
      (setq zwk:loadset (cons "trim" zwk:loadset)))
    ;; module file -> selection key; nil key = always loaded (foundational)
    (setq zwk:modkeys '(("modules/dimensions.lsp" . "dimensions")
                         ("modules/trim.lsp" . "trim")
                         ("modules/extend.lsp" . "extend")
                         ("modules/click.lsp" . nil)
                         ("modules/dimcore.lsp" . nil)
                         ("modules/tolerance.lsp" . "tolerance")
                         ("modules/symbols.lsp" . "symbols")
                         ("modules/font.lsp" . "font")
                         ("modules/dimline.lsp" . "dimline")))
    (foreach zwk:m zwk:modules
      (setq zwk:key (cdr (assoc zwk:m zwk:modkeys)))
      (if (or (null zwk:key) (member zwk:key zwk:loadset))
        (load (strcat zwk:root "/" zwk:m))))
    (if (not (member "dimensions" zwk:enabled))
      (setq c:ZD nil c:ZD2 nil c:ZDO nil c:ZDB nil c:ZDJ nil c:ZDJ3 nil))
    ;; click.lsp 常驻点选版 TR/EX：已定义时不再回退原生命令。
    (if (not (member "trim" zwk:enabled))
      (progn (if (not c:TR) (defun c:TR () (command "_.TRIM") (princ))) (setq c:ZT nil c:ZTY nil)))
    (if (not (member "extend" zwk:enabled))
      (progn (if (not c:EX) (defun c:EX () (command "_.EXTEND") (princ))) (setq c:EXY nil)))
    (if (not (member "tolerance" zwk:enabled)) (setq c:GC nil))
    (if (not (member "symbols" zwk:enabled)) (setq c:FH nil))
    (if (not (member "font" zwk:enabled)) (setq c:ZF nil c:ZFD nil))
    (if (not (member "dimline" zwk:enabled)) (setq c:BZ nil c:BZD nil))
    (zwk:smooth)
    (princ "\n工具包已按安装选项加载，用 ZWKCHECK 自检。"))
  (princ "\n工具包路径缺失，请重新一键安装。"))
(princ)
